version: "3"
services:
  reearth:
    image: reearth/reearth:latest
    environment:
      REEARTH_DB: mongodb://reearth-mongo
    ports:
      - 8080:8080
    # env_file:
    #  - ./.env
    links:
      - reearth-mongo
    depends_on:
      - reearth-mongo
    volumes:
      - ./data:/reearth/data
  reearth-mongo:
    image: mongo:5-focal
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
  reearth-redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
  # docker run --rm --name cerbos -d -v $(pwd)/policies:/policies -p 3592:3592 -p 3593:3593 ghcr.io/cerbos/cerbos:0.36.0
  reearth-cerbos:
    image: ghcr.io/cerbos/cerbos:0.36.0
    ports:
      - 3592:3592
      - 3593:3593
    volumes:
      - ./policies:/policies
