[build]
  base = "web/"
  publish = "web/dist"
  command = "yarn build:preview && (cd dist && curl -O https://test.reearth.dev/reearth_config.json)"

[[redirects]]
  from = "/web/*"
  to = "/web/index.html"
  status = 200
