name: build-server
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch'
        required: true
      ref:
        description: 'Ref'
        required: false
  repository_dispatch:
    types: [build-server]
jobs:
  info:
    name: Collect information
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.info.outputs.sha_short }}
      new_tag: ${{ steps.info.outputs.new_tag }}
      new_tag_short: ${{ steps.info.outputs.new_tag_short }}
      name: ${{ steps.info.outputs.name }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.ref.head_sha }}
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags
      - name: Get info
        id: info
        # The tag name should be retrieved lazily, as tagging may be delayed.
        env:
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "BRANCH=$BRANCH"
          if [[ "$BRANCH" = "release" || "$BRANCH" = "release/"* ]]; then
            TAG=$(git tag --points-at HEAD)
            if [[ ! -z "$TAG" ]]; then
              echo "::set-output name=new_tag::$TAG"
              echo "::set-output name=new_tag_short::${TAG#v}"
            else
              echo "::set-output name=name::rc"
            fi
          else
            echo "::set-output name=name::nightly"
          fi
      - name: Show info
        env:
          SHA_SHORT: ${{ steps.info.outputs.sha_short }}
          NEW_TAG: ${{ steps.info.outputs.new_tag }}
          NEW_TAG_SHORT: ${{ steps.info.outputs.new_tag_short }}
          NAME: ${{ steps.info.outputs.name }}
        run: echo "sha_short=$SHA_SHORT, new_tag=$NEW_TAG, new_tag_short=$NEW_TAG_SHORT, name=$NAME"

  build-server:
    name: Build and release server
    runs-on: ubuntu-latest
    needs: [info]
    if: needs.info.outputs.name || needs.info.outputs.new_tag
    env:
      ARTIFACTS: server/dist/reearth_*.*
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist ${{ env.SNAPSHOT }}
          workdir: server
        env:
          SNAPSHOT: ${{ !needs.info.outputs.new_tag && '--snapshot' || '' }}
          GORELEASER_CURRENT_TAG: ${{ needs.info.outputs.new_tag || '0.0.0' }}
      - name: Rename artifacts
        if: needs.info.outputs.name
        run: for f in $ARTIFACTS; do mv $f $(echo $f | sed -E 's/_0\.0\.0-SNAPSHOT-[^_]*/_${{ needs.info.outputs.name }}/'); done
      - name: List artifacts
        run: ls -l server/dist
      - name: Release nightly/rc
        if: needs.info.outputs.name
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ env.ARTIFACTS }}
          commit: ${{ github.sha }}
          name: ${{ needs.info.outputs.name }}
          tag: ${{ needs.info.outputs.name }}
          body: ${{ needs.info.outputs.sha_short }}
          prerelease: true
      - name: Download latest changelog
        if: needs.info.outputs.new_tag
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: release.yml
          name: changelog-${{ needs.info.outputs.new_tag }}
      - name: Create GitHub release
        if: needs.info.outputs.new_tag
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.ARTIFACTS }}
          commit: ${{ github.sha }}
          name: ${{ needs.info.outputs.new_tag }}
          tag: ${{ needs.info.outputs.new_tag}}
          bodyFile: CHANGELOG_latest.md

  build-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: [info]
    if: needs.info.outputs.name || needs.info.outputs.new_tag
    env:
      IMAGE_NAME: reearth/reearth
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get options
        id: options
        env:
          TAG: ${{ needs.info.outputs.new_tag_short }}
          NAME: ${{ needs.info.outputs.name }}
          SHA: ${{ needs.info.outputs.sha_short }}
        run: |
          if [[ -n $TAG ]]; then
            PLATFORMS=linux/amd64,linux/arm64
            VERSION=$TAG
            TAGS=$IMAGE_NAME:$TAG
            if [[ ! $TAG =~ '-' ]]; then
              TAGS+=,${IMAGE_NAME}:${TAG%.*}
              TAGS+=,${IMAGE_NAME}:${TAG%%.*}
              TAGS+=,${IMAGE_NAME}:latest
            fi
          else
            PLATFORMS=linux/amd64
            VERSION=$SHA
            TAGS=$IMAGE_NAME:$NAME
          fi
          echo "::set-output name=platforms::$PLATFORMS"
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=tags::$TAGS"
      - name: Fetch reearth-web release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: reearth/reearth
          version: tags/${{ needs.info.outputs.name || needs.info.outputs.tag }}
          file: reearth-web_${{ needs.info.outputs.name || needs.info.outputs.tag }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          target: server/reearth-web.tar.gz
      - name: Extract reearth/web
        run: tar -xvf reearth-web.tar.gz; mv reearth-web web; ls
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: server
          platforms: ${{ steps.options.outputs.platforms }}
          push: true
          build-args: VERSION=${{ steps.options.outputs.version }}
          tags: ${{ steps.options.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Invoke ci-deploy-server-nightly workflow
        uses: benc-uk/workflow-dispatch@v1
        if: needs.info.outputs.name == 'nightly'
        with:
          workflow: deploy-server-nightly
          token: ${{ secrets.GPT }}
