name: ci
on:
  push:
    branches: [main, release/*, release]
  pull_request:
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.web.outputs.any_changed }}
      server: ${{ steps.server.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: changed files for web
        id: web
        uses: tj-actions/changed-files@v36
        with:
          files: |
            web
            .github/workflows/ci.yml
            .github/workflows/ci_web.yml
            .github/workflows/ci_web_build.yml
            .github/workflows/ci_deploy_web_nightly.yml

      - name: changed files for server
        id: server
        uses: tj-actions/changed-files@v36
        with:
          files: |
            server
            .github/workflows/ci.yml
            .github/workflows/ci_server.yml
            .github/workflows/ci_server_build.yml
            .github/workflows/ci_deploy_server_nightly.yml
  ci-web:
    needs: prepare
    if: needs.prepare.outputs.web == 'true'
    uses: ./.github/workflows/ci_web.yml
  ci-server:
    needs: prepare
    if: needs.prepare.outputs.server == 'true'
    uses: ./.github/workflows/ci_server.yml
  ci:
    runs-on: ubuntu-latest
    needs:
      - ci-web
      - ci-server
    if: '!failure()'
    steps:
      - run: echo OK
  build-web:
    needs: 
      - ci
      - ci-web
    runs-on: ubuntu-latest
    if: $${{!failure() && github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'release' || startsWith(github.ref_name, 'release/'))}}
    steps:
      - name: Dispatch Web Build
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: build-web
  build-server:
    needs: 
      - ci
      - ci-server
    runs-on: ubuntu-latest
    if: ${{!failure() && github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'release' || startsWith(github.ref_name, 'release/'))}}
    steps:
      - name: Dispatch Web Build
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: build-server