name: build-push-docker
on:
  workflow_dispatch:
    inputs:
      sha_short:
        description: 'sha_short'
        required: true
      tag:
        description: 'tag'
        required: true
jobs:
  build-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    if: github.event.inputs.tag
    env:
      IMAGE_NAME: reearth/reearth
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get options
        id: options
        env:
          TAG: ${{ github.event.inputs.tag }}
          SHA: ${{ github.event.inputs.sha_short }}
        run: |
          PLATFORMS=linux/amd64
          VERSION=$SHA
          TAGS=$IMAGE_NAME:$TAG
          echo "::set-output name=platforms::$PLATFORMS"
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=tags::$TAGS"
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: server
          platforms: ${{ steps.options.outputs.platforms }}
          push: true
          build-args: VERSION=${{ steps.options.outputs.version }}
          tags: ${{ steps.options.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max