name: ci-server
on:
  push:
    branches: [main, release/*]
    paths:
      - server/**
  pull_request:
    paths:
      - server/**

jobs:
  ci:
    name: Check server change
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    services:
      mongo:
        image: mongo:6-focal
        ports:
          - 27017:27017
    steps:
      - name: set up
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"
      - name: checkout
        uses: actions/checkout@v3
      - name: cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52
          args: --timeout=10m
          working-directory: server
      - name: test
        run: go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic -timeout 10m
        env:
          REEARTH_DB: mongodb://localhost
        working-directory: server
      - name: Send coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: server