name: ci-web
on:
  push:
    branches: [main, release/*]
    paths:
      - web/**
  pull_request:
    paths:
      - web/**

jobs:
  ci:
    name: Check and build web change
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version-file: "web/.nvmrc"
        - name: Get yarn cache directory path
          id: yarn-cache-dir-path
          run: echo "::set-output name=dir::$(yarn cache dir)"
        - uses: actions/cache@v3
          id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
          with:
            path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
            key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-yarn-
        - name: Install
          run: yarn install
        - name: Check
          run: yarn run check
        - name: Test
          run: yarn run coverage
        - name: Check translations
          run: yarn i18n --fail-on-update
        - name: Send coverage report
          uses: codecov/codecov-action@v2
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            flags: web
